### ISSUE TITLE
Incompatible with the latest Flutter beta (2.5.0-5.1.pre)

### ISSUE THREAD

**Issue by josh-burton** [marcglasberg/assorted_layout_widgets#14]
```
../../../../.pub-cache/hosted/pub.dartlang.org/assorted_layout_widgets-5.0.2/lib/src/text_one_line_ellipsis_with_fade.dart:995:20: Error: The method 'RenderParagraphX.getBoxesForSelection' has fewer named arguments than those of overridden method 'RenderParagraph.getBoxesForSelection'.
  List<ui.TextBox> getBoxesForSelection(TextSelection selection) {
```

**Comment by carmas123** [comment]
Also with 2.5.0 (non beta obviously)

**Comment by MrCsabaToth** [comment]
PR available for a month now, 2.5 is stable

**Comment by eldarkk** [comment]
temporarily use this one:
```
assorted_layout_widgets:
    git:
        url: git://github.com/eldarkk/assorted_layout_widgets.git
```

**Comment by MrCsabaToth** [comment]
No need to open an `n+1` repo, the PR's repo is there for a month:
```
assorted_layout_widgets:
    git:
         url: https://github.com/josh-burton/assorted_layout_widgets.git
         ref: beta-fix
```
